sudo: required
dist: trusty

group: edge

# whitelist
branches:
  only:
    - master

notifications:
  irc:
    channels:
      - "irc.uvt.nl#gitlama"
    template:
      - "%{repository_slug}#%{build_number} %{message} --> %{build_url}"
    skip_join: true

language: cpp
matrix:
  include:
    - os: linux
      compiler: gcc

    - os: linux
      compiler: clang

    - os: osx
      compiler: gcc


before_install:
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
        sudo apt-get update;
        sudo apt-get install pkg-config autoconf-archive libicu-dev libexttextcat-dev;
      fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
        brew update;
        brew install pkg-config;
        brew install autoconf-archive;
        brew install icu4c;
        brew install libtextcat;
      fi

install:
    - bash bootstrap.sh
    - ./configure
    - make
    - sudo make install
#    - ls -al /usr/lib/x86_64-linux-gnu/lib*omp.so

script:
    - LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib make CXX=$COMPILER check

after_failure:
    - tail -n500 config.log
    - cat src/test-suite.log
