sudo: required
dist: trusty

group: edge

# whitelist
branches:
  only:
    - master

notifications:
  irc:
    channels:
      - "irc.uvt.nl#gitlama"
    template:
      - "%{repository_slug}#%{build_number} %{message} --> %{build_url}"
    skip_join: true

language: cpp
matrix:
  include:
    - os: linux
      compiler: gcc

    - os: linux
      compiler: clang++
      addons:
        apt:
          packages:
# openmp on travis/trusty is a mess. Just disable for now...
#            - libiomp-dev
      env:
        - OPENMPFLAG=--disable-openmp

    - os: osx
      compiler: clang++

before_install:
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
        sudo apt-get update;
        sudo apt-get install pkg-config autoconf-archive libicu-dev libexttextcat-dev;
      fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
        brew update;
        brew install pkg-config;
        brew install autoconf-archive;
        brew outdated icu4j || brew install icu4c;
        brew install libtextcat;
      fi

install:
    - bash bootstrap.sh
    - ./configure $OPENMPFLAG
    - make
    - sudo make install

script:
    - LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib make check
    - cat src/tst.log
    - cat config.log

after_failure:
    - cat src/tst.log
    - cat config.log
    - cat src/test-suite.log
