name: 'Get Status'
description: 'sets the action_status environment var'

inputs:
  the-step:
    description: 'which step to check'
    required: true
  outcome:
    description: 'which outcome'
    required: true

runs:
  using: "composite"
  steps:
    - name: doit
      shell: bash
      if: ${{ inputs.outcome != 'success' }}
      run: |
        echo "outcome= ${{ inputs.outcome }}"
        echo "action_status=${{ inputs.the-step }}" >> $GITHUB_ENV
