name: C/C++ CI

on:
  schedule:
    - cron: "0 22 3 * 5"  # run test once a month
  push:
    branches: [master]
    paths:
      - configure.ac
      - 'src/**'
      - 'include/**'
      - '.github/workflows/*'

  pull_request:
    branches: [master]

jobs:
  notification:
    runs-on: ubuntu-latest
    name: Notifications
    outputs:
      branch: ${{ steps.extract_branch.outputs.branch }}
    steps:
      - name: Extract Branch name
        id: extract_branch
        shell: bash
        run: echo "branch=$(echo ${GITHUB_REF#refs/heads/})" >> $GITHUB_OUTPUT
      - name: IRC notification
        uses: Gottox/irc-message-action@v2
        with:
          server: irc.uvt.nl
          channel: '#gitlama'
          nickname: GitHub
          message: >
            ${{ github.actor }} started a build of unicodetest
            [${{ steps.extract_branch.outputs.branch }}]

  build:
    runs-on: ${{ matrix.os }}
    needs: notification
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        compiler: [g++-12, clang++]

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.12.1
        with:
          access_token: ${{ github.token }}

      - uses: actions/checkout@v4.1.1

      - name: Install Build Environment
        run: |
             if [ "$RUNNER_OS" == "Linux" ]; then
                sudo apt-get install pkgconf autoconf-archive
             else
                brew upgrade
                brew install libtool
                brew install autoconf
                brew install autoconf-archive
                brew install automake
             fi

      - name: Install Dependencies
        run: |
             if [ "$RUNNER_OS" == "Linux" ]; then
                sudo apt-get install libicu-dev libxml2-dev libbz2-dev;
                sudo apt-get install zlib1g-dev
             else
                brew install libxml2
                brew reinstall icu4c
                brew install bzip2
                brew install zlib
             fi

      - name: bootstrap
        run: sh bootstrap.sh

      - name: configure
        env:
          CXX: ${{ matrix.compiler }}
        run: ./configure
        continue-on-error: true
      - name: config.log
        if: ${{ steps.configure.outcome != 'success' }}
        run: cat config.log
      - name: make
        env:
          CXX: ${{ matrix.compiler }}
        run: make
        continue-on-error: true
      - name: install
        env:
          CXX: ${{ matrix.compiler }}
        run: sudo make install
        continue-on-error: true
      - id: compiler
        run: |
          cid=$(echo ${{matrix.compiler}} | cut -d\+ -f1)
          echo "cid=$cid" >> $GITHUB_ENV
      - name: make check
        id: check
        env:
          CXX: ${{ matrix.compiler }}
          LD_LIBRARY_PATH: $LD_LIBRARY_PATH:/usr/local/lib
        run: make check
        continue-on-error: true
      - name: get check_status
        uses: ./.github/workflows/get_status.yml
        with:
          step: ${{ check }}
      - name: show status
        run: echo STATUS=${{ env.action_status }}
      - name: show log
        if: ${{ steps.check.outcome != 'success' }}
        run: cat src/test-suite.log
        continue-on-error: true
      - name: Notify IRC of failure
        if: ${{ steps.check.outcome != 'success' }}
        uses: Gottox/irc-message-action@v2
        with:
          server: irc.uvt.nl
          channel: '#gitlama'
          nickname: GH-${{ runner.os }}-${{ env.cid }}
          message: "unicodetest [${{ needs.notification.outputs.branch }}] build with ${{ matrix.compiler }} by ${{ github.actor }} on ${{ matrix.os }}: \u00034FAILED\u0003"
      - name: Notify IRC of succes
        if: ${{ steps.check.outcome == 'success' }}
        uses: Gottox/irc-message-action@v2
        with:
          server: irc.uvt.nl
          channel: '#gitlama'
          nickname: GH-${{ runner.os }}-${{ env.cid }}
          message: "unicodetest [${{ needs.notification.outputs.branch }}] build with ${{ matrix.compiler }} by ${{ github.actor }} on ${{ matrix.os }}: \u00033SUCCESS\u0003"
